version: '2'
services:

  # data only container pattern
  data:
    image: debian:jessie
    volumes:
      - .:/data

  changelog:
    image: muccg/github-changelog-generator:latest
    network_mode: host
    environment:
      something: somevalue
    volumes_from:
      - data
